# Generated by Django 5.2.4 on 2025-07-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('invoice_number', models.CharField(max_length=100)),
                ('purchase_date', models.DateField()),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('current_location', models.CharField(max_length=100)),
                ('supplier_name', models.CharField(max_length=100)),
                ('working_status', models.CharField(choices=[('working', 'Working'), ('not_working', 'Not Working'), ('repair', 'Under Repair'), ('disposed', 'Disposed')], max_length=50)),
                ('current_custodian', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
