# Generated by Django 5.2.4 on 2025-07-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_asset_warranty_end_date_alter_asset_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='working_status',
            field=models.CharField(max_length=50),
        ),
    ]
