# Generated by Django 5.2.4 on 2025-07-21 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.store'),
        ),
    ]
