# Generated by Django 5.2.4 on 2025-07-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_asset_previous_custodian_asset_previous_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='current_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='working_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
